#ifndef __EXIT_CODE_H__
#define __EXIT_CODE_H__

#define LOGICAL_ERROR 1
#define VERSION_FILE_NOT_EXIST 2
#define VERSION_STRING_TOO_SHORT 3
#define MEMINFO_FILE_NOT_EXIST 4
#define MEMINFO_STRING_TOO_SHORT 5
#define CREATE_PROCESS_FILE_FAILURE 6
#define DLOPEN_ERROR 7
#define DLSYM_ERROR 8
#define HTML_OPEN_ERROR 9

#endif